#!/bin/bash

sbatch reps-sum-01.sh
sbatch reps-sum-02.sh
sbatch reps-sum-03.sh
sbatch reps-sum-04.sh
sbatch reps-sum-05.sh
sbatch reps-sum-06.sh
sbatch reps-sum-07.sh
sbatch reps-sum-08.sh
sbatch reps-sum-09.sh
sbatch reps-sum-10.sh
sbatch reps-sum-11.sh
sbatch reps-sum-12.sh
sbatch reps-sum-13.sh
sbatch reps-sum-14.sh
sbatch reps-sum-15.sh
sbatch reps-sum-16.sh
sbatch reps-sum-17.sh
sbatch reps-sum-18.sh
sbatch reps-sum-19.sh
sbatch reps-sum-20.sh
sbatch reps-sum-21.sh
sbatch reps-sum-22.sh
sbatch reps-sum-23.sh
sbatch reps-sum-24.sh
sbatch reps-sum-25.sh
sbatch reps-sum-26.sh
sbatch reps-sum-27.sh
