---
title: "Containers"
author: Ivan Jacob Agaloos Pesigan
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Containers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



**[Docker](https://www.docker.com/) and [Apptainer](https://apptainer.org/) are required to build the containers described below.**

## Apptainer/Singularity Image File

The simulation was performed using the [Apptainer/Singularity](https://apptainer.org/) `manmetavar.sif` image file. The image is a linux container with the `manMetaVAR` package and all the dependencies pre-installed.

To build the Apptainer/Singularity image file (`manmetavar.sif`),
run the following.

```bash
apptainer pull manmetavar.sif docker://ijapesigan/manmetavar:2025-04-07-05390291
```

## RStudio IDE Docker Container

To facilitate exploration of the package, we created a Docker container based on the [Rocker Project](https://rocker-project.org/). The `manMetaVAR` package and all the dependencies are pre-installed and can be accessed in the browser using the `Rstudio` IDE.

### Run

To launch `Rstudio Server`, run the following.

```bash
docker run --rm -ti -e PASSWORD=yourpassword -p 127.0.0.1:8787:8787 ijapesigan/manmetavar:2025-04-07-05390291
```

Open `http://localhost:8787` on your web browser to launch `Rstudio Server`.

- username: rstudio
- password: yourpassword

> **NOTE**: `Mplus` is closed-source and proprietary software, so it cannot be included in publicly available containers. Consequently, some functions that require `Mplus` will not work in these containers.
