---
title: "Empirical Illustration: Meta-Analysis of Affect Dynamics"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Empirical Illustration: Meta-Analysis of Affect Dynamics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





## Data Pre-Processing

This illustration uses ecological momentary assessment (EMA) data from the Affective Dynamics and Individual Differences (ADID) study. To align the data with the discrete-time VAR framework used in this vignette, we first rounded each response timestamp to the nearest hour and then constructed an hourly, regularly spaced time series for each participant. Hours with no observed response were retained as missing so that the lagged effects could be interpreted on an approximately hourly timescale.

We then created per-occasion negative affect (NA) and positive affect (PA) composites by averaging the available negative-affect and positive-affect item responses, respectively. Because the raw EMA series also contain slower month-long drift, we applied within-person linear detrending before model fitting. Under this preprocessing scheme, the resulting VAR model targets a short-term, detrended, approximately hourly affective process rather than the full raw trajectory.

The full preprocessing script used to generate the analysis dataset is available here:

<https://raw.githubusercontent.com/jeksterslab/manMetaVAR/refs/heads/main/.setup/data-analysis/data-analysis-empirical-data-ema.R>



## Stage 1: Person-Specific VAR


``` r
library(OpenMx)
library(fitVARMxID)
stage1 <- FitVARMxID(
  data = data,
  observed = c("na", "pa"),
  id = "id",
  center = TRUE,
  ncores = parallel::detectCores()
)
```


``` r
summary(stage1, means = TRUE)
#> Call:
#> FitVARMxID(data = data, observed = c("na", "pa"), id = "id", 
#>     center = TRUE, seed = 42, tries_explore = 1000, tries_local = 1000, 
#>     max_attempts = 100, ncores = parallel::detectCores())
#> 
#> Convergence:
#> 100.0%
#> 
#> Means of the estimated paramaters per individual.
#>   mu[1,1]   mu[2,1] beta[1,1] beta[2,1] beta[1,2] beta[2,2]  psi[1,1]  psi[2,1] 
#>    1.4426    2.5733    0.3432   -0.0965   -0.0470    0.2857    0.0388   -0.0109 
#>  psi[2,2] 
#>    0.0701
```

## Stage 2: Multivariate Random-Effects Meta-Analysis of the Dynamic Parameter System


``` r
library(metaDyn)
stage2 <- MetaVARMx(
  object = stage1,
  random = TRUE,
  ncores = parallel::detectCores()
)
```


``` r
summary(stage2)
#> Call:
#> MetaVARMx(object = stage1, random = TRUE, ncores = parallel::detectCores())
#> 
#> Status code:
#> 0
#> 
#> Confidence intervals type:
#> Wald
#> 
#> Sampling covariance matrix type:
#> Normal
#> 
#>                  est     se          z      p    2.5%   97.5%
#> alpha[1,1]    1.4417 0.0253    57.0792 0.0000  1.3922  1.4912
#> alpha[2,1]    2.5731 0.0322    79.7961 0.0000  2.5099  2.6363
#> alpha[3,1]    0.3825 0.0316    12.1220 0.0000  0.3207  0.4444
#> alpha[4,1]   -0.0948 0.0335    -2.8271 0.0047 -0.1606 -0.0291
#> alpha[5,1]   -0.0388 0.0185    -2.0911 0.0365 -0.0751 -0.0024
#> alpha[6,1]    0.3285 0.0318    10.3434 0.0000  0.2663  0.3908
#> alpha[7,1]    0.0318 0.0018    17.4267 0.0000  0.0282  0.0354
#> alpha[8,1]   -0.0079 0.0009    -8.3110 0.0000 -0.0097 -0.0060
#> alpha[9,1]    0.0623 0.0029    21.3148 0.0000  0.0565  0.0680
#> tau_sqr[1,1]  0.1338 0.0132    10.1595 0.0000  0.1080  0.1596
#> tau_sqr[2,1]  0.0087 0.0119     0.7359 0.4618 -0.0145  0.0320
#> tau_sqr[3,1]  0.0204 0.0117     1.7418 0.0815 -0.0026  0.0434
#> tau_sqr[4,1] -0.0005 0.0120    -0.0419 0.9666 -0.0240  0.0230
#> tau_sqr[5,1]  0.0141 0.0070     2.0075 0.0447  0.0003  0.0279
#> tau_sqr[6,1] -0.0038 0.0116    -0.3310 0.7406 -0.0266  0.0189
#> tau_sqr[7,1]  0.0036 0.0007     5.0435 0.0000  0.0022  0.0050
#> tau_sqr[8,1] -0.0001 0.0003    -0.4513 0.6517 -0.0008  0.0005
#> tau_sqr[9,1] -0.0020 0.0010    -1.9083 0.0564 -0.0041  0.0001
#> tau_sqr[2,2]  0.2185 0.0214    10.2324 0.0000  0.1767  0.2604
#> tau_sqr[3,2]  0.0033 0.0148     0.2249 0.8220 -0.0257  0.0323
#> tau_sqr[4,2]  0.0020 0.0153     0.1325 0.8946 -0.0280  0.0320
#> tau_sqr[5,2]  0.0072 0.0086     0.8352 0.4036 -0.0097  0.0241
#> tau_sqr[6,2]  0.0016 0.0148     0.1112 0.9115 -0.0274  0.0307
#> tau_sqr[7,2] -0.0017 0.0008    -2.0910 0.0365 -0.0034 -0.0001
#> tau_sqr[8,2]  0.0006 0.0004     1.4502 0.1470 -0.0002  0.0013
#> tau_sqr[9,2] -0.0045 0.0014    -3.3261 0.0009 -0.0072 -0.0019
#> tau_sqr[3,3]  0.1898 0.0202     9.3930 0.0000  0.1502  0.2294
#> tau_sqr[4,3] -0.0304 0.0156    -1.9470 0.0515 -0.0611  0.0002
#> tau_sqr[5,3]  0.0200 0.0088     2.2611 0.0238  0.0027  0.0373
#> tau_sqr[6,3]  0.0025 0.0145     0.1686 0.8661 -0.0260  0.0309
#> tau_sqr[7,3] -0.0010 0.0008    -1.2298 0.2188 -0.0026  0.0006
#> tau_sqr[8,3]  0.0011 0.0004     2.8000 0.0051  0.0003  0.0019
#> tau_sqr[9,3] -0.0021 0.0013    -1.6118 0.1070 -0.0047  0.0005
#> tau_sqr[4,4]  0.1747 0.0260     6.7248 0.0000  0.1238  0.2256
#> tau_sqr[5,4]  0.0077 0.0082     0.9465 0.3439 -0.0083  0.0237
#> tau_sqr[6,4]  0.0411 0.0158     2.6076 0.0091  0.0102  0.0720
#> tau_sqr[7,4]  0.0003 0.0008     0.3322 0.7398 -0.0014  0.0019
#> tau_sqr[8,4] -0.0006 0.0004    -1.5445 0.1225 -0.0014  0.0002
#> tau_sqr[9,4] -0.0024 0.0014    -1.6620 0.0965 -0.0051  0.0004
#> tau_sqr[5,5]  0.0578 0.0075     7.7007 0.0000  0.0431  0.0726
#> tau_sqr[6,5] -0.0293 0.0089    -3.3041 0.0010 -0.0467 -0.0119
#> tau_sqr[7,5] -0.0009 0.0005    -1.7514 0.0799 -0.0019  0.0001
#> tau_sqr[8,5]  0.0000 0.0002     0.0157 0.9875 -0.0005  0.0005
#> tau_sqr[9,5]  0.0006 0.0008     0.8032 0.4219 -0.0009  0.0021
#> tau_sqr[6,6]  0.1891 0.0203     9.3171 0.0000  0.1493  0.2288
#> tau_sqr[7,6]  0.0007 0.0008     0.8924 0.3722 -0.0009  0.0024
#> tau_sqr[8,6] -0.0007 0.0004    -1.8590 0.0630 -0.0015  0.0000
#> tau_sqr[9,6] -0.0036 0.0013    -2.7092 0.0067 -0.0062 -0.0010
#> tau_sqr[7,7]  0.0006 0.0001     7.8407 0.0000  0.0005  0.0008
#> tau_sqr[8,7] -0.0002 0.0000    -5.3299 0.0000 -0.0002 -0.0001
#> tau_sqr[9,7]  0.0003 0.0001     4.0348 0.0001  0.0002  0.0005
#> tau_sqr[8,8]  0.0001 0.0000     5.8213 0.0000  0.0001  0.0002
#> tau_sqr[9,8] -0.0002 0.0000    -4.6396 0.0000 -0.0003 -0.0001
#> tau_sqr[9,9]  0.0015 0.0002     8.0111 0.0000  0.0012  0.0019
#> i_sqr[1,1]    0.9989 0.0001  9358.3461 0.0000  0.9987  0.9991
#> i_sqr[2,1]    0.9973 0.0003  3802.4263 0.0000  0.9968  0.9978
#> i_sqr[3,1]    0.9662 0.0035   278.0353 0.0000  0.9594  0.9730
#> i_sqr[4,1]    0.9329 0.0093   100.1879 0.0000  0.9146  0.9511
#> i_sqr[5,1]    0.9483 0.0064   148.9629 0.0000  0.9358  0.9608
#> i_sqr[6,1]    0.9514 0.0050   191.5564 0.0000  0.9416  0.9611
#> i_sqr[7,1]    0.9999 0.0000 56654.7579 0.0000  0.9998  0.9999
#> i_sqr[8,1]    0.9992 0.0001  7703.0848 0.0000  0.9990  0.9995
#> i_sqr[9,1]    0.9961 0.0005  2040.8582 0.0000  0.9951  0.9970
```


