#' Bayesian Mplus Diagnostics Across Simulation Conditions
#'
#' Parameter- and run-level Bayesian Mplus diagnostics for all simulation task
#' IDs and both prior specifications.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @docType data
#' @name diagnostics
#' @usage data(diagnostics)
#' @format A list with three elements:
#'
#' \describe{
#'   \item{parameters}{A data frame with one row per task ID, replication,
#'     prior condition, and Mplus parameter. It contains the simulation design
#'     variables, posterior summaries, R-hat, bulk and tail ESS, and MCSEs.}
#'   \item{runs}{A data frame with one row per task ID, replication, and prior
#'     condition containing run-level diagnostics and elapsed time.}
#'   \item{replications}{Number of simulation replications represented in each
#'     task/prior cell.}
#' }
#'
#' The object is generated by
#' `.setup/data-process/data-process-z-diagnostics.R` from the task-specific
#' outputs of [SumFitMplusDiagnostics()] and
#' [SumFitMplusPriorsDiagnostics()].
#'
#' @keywords data diagnostics simulation
"diagnostics"
