#' Bayesian Mplus Diagnostics Across Simulation Conditions
#'
#' Parameter- and run-level Bayesian Mplus diagnostics
#' for all simulation task IDs,
#' stored separately for the default and alternative prior specifications.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @docType data
#' @name diagnostics
#' @aliases diagnostics_default diagnostics_priors
#' @usage data(diagnostics_default)
#' data(diagnostics_priors)
#' @format A list with three elements:
#'
#' \describe{
#'   \item{parameters}{A data frame with one row per task ID, replication,
#'     prior condition, and Mplus parameter.
#'     It contains the simulation design variables,
#'     posterior SD, R-hat, bulk and tail ESS, and MCSEs.}
#'   \item{runs}{A data frame with one row per task ID, replication, and prior
#'     condition containing run-level diagnostics and elapsed time.}
#'   \item{replications}{Number of simulation replications represented in each
#'     task/prior cell.}
#' }
#'
#' The object is generated by
#' `.setup/data-process/data-process-005-diagnostics.R` from the task-specific
#' outputs of [SumFitMplusDiagnostics()] and
#' [SumFitMplusPriorsDiagnostics()].
#'
#' @details
#' Each bundle covers 36 bivariate tasks and one prior branch, with
#' 1,000 replications per task/prior cell: 36,000 run rows and
#' 792,000 parameter rows (22 parameters per run). Use [LoadMplusDiagnostics()]
#' to combine the bundles into 72,000 run rows and 1,584,000 parameter rows.
#' The separate bundles replace `data(diagnostics)` and the earlier
#' 10-replication bundle. Block-level failures differ from full-run gates.
#' Primary thresholds are Rhat >1.01, bulk/tail ESS <400, MCSE/SD >0.05;
#' nonfinite diagnostics fail. These are archived summaries, not new fits.
#'
#' The compact parameter tables omit posterior means, medians,
#' and interval endpoints (`mean`, `median`, `ll`, and `ul`)
#' to reduce bundle size. Posterior SD (`sd`), R-hat, bulk and
#' tail ESS, and all four MCSE columns are retained without rounding or
#' subsampling. Run diagnostics and replication counts are unchanged.
#' The complete posterior summaries remain in the task-specific source files.
#' @keywords data diagnostics simulation
"diagnostics_default"
