#' Bayesian Diagnostic Heatmaps Across Simulation Conditions
#'
#' Summarize parameter-level Mplus Bayesian diagnostics across all simulation
#' task IDs and display them using the same design-cell-by-parameter layout as
#' [FigMetricHeatmap()]. The function can display the two prior conditions
#' directly or paired user-prior minus default-prior differences.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param diagnostics An all-task diagnostic object containing a
#'   `parameters` data frame, such as the `diagnostics` object generated by
#'   `.setup/data-process/data-process-z-diagnostics.R`. A parameter-level data
#'   frame may also be supplied directly.
#' @param metric_name Character string. Valid values are `"failure_rate"`,
#'   `"rhat"`, `"ess"`, and `"mcse"`.
#' @param comparison Character string. Use `"levels"` to show default and
#'   user-specified priors or `"difference"` to show paired user-prior minus
#'   default-prior differences.
#' @param diagnostic Optional diagnostic panel names to retain. If `NULL`, all
#'   panels for the selected metric are displayed.
#' @param taskid Optional positive integer task IDs to include. The default is
#'   to summarize all task IDs.
#' @param parm Parameter names or positive integer positions to include. If
#'   `NULL`, all k = 2 Mplus parameters are included.
#' @param center Character string indicating whether continuous diagnostics
#'   are summarized using the `"mean"` or `"median"` across replications.
#'   Failure rates always use the mean.
#' @param rhat_threshold Numeric R-hat threshold.
#' @param ess_threshold Numeric bulk and tail ESS threshold.
#' @param mcse_threshold Numeric MCSE threshold.
#' @param relative_mcse Logical. If `TRUE`, Monte Carlo standard errors are
#'   divided by the posterior standard deviation before summarizing.
#' @param grey_scale Logical. If `TRUE`, use a grey-scale fill.
#' @param values Logical. If `TRUE`, print summarized values inside cells.
#'
#' @return A `ggplot` object. Its `data` element contains the all-task summary
#'   used in the heatmap.
#'
#' @details
#' Failure rates count nonfinite diagnostic values as failures. For
#' `comparison = "difference"`, diagnostic values are paired by task ID,
#' replication, parameter, and diagnostic before computing user-prior minus
#' default-prior differences. Blue cells indicate improvement under user
#' priors and red cells indicate deterioration.
#'
#' @examples
#' \dontrun{
#' data(diagnostics, package = "manMetaVAR")
#'
#' FigMplusDiagnosticsHeatmap(
#'   diagnostics = diagnostics,
#'   metric_name = "failure_rate",
#'   comparison = "difference"
#' )
#'
#' FigMplusDiagnosticsHeatmap(
#'   diagnostics = diagnostics,
#'   metric_name = "rhat",
#'   comparison = "levels",
#'   values = TRUE
#' )
#' }
#'
#' @family Figure Functions
#' @keywords manMetaVAR figure diagnostics simulation sensitivity
#' @export
FigMplusDiagnosticsHeatmap <- function(diagnostics,
                                       metric_name = "failure_rate",
                                       comparison = "difference",
                                       diagnostic = NULL,
                                       taskid = NULL,
                                       parm = NULL,
                                       center = "mean",
                                       rhat_threshold = 1.01,
                                       ess_threshold = 400,
                                       mcse_threshold = 0.05,
                                       relative_mcse = TRUE,
                                       grey_scale = FALSE,
                                       values = FALSE) {
  condition_label <- parameter_label <- fill_value <- NULL
  value_label <- text_colour <- heterogeneity_label <- target <- NULL
  method <- diagnostic_panel <- NULL
  metric_name <- match.arg(
    arg = metric_name,
    choices = c(
      "failure_rate",
      "rhat",
      "ess",
      "mcse"
    )
  )
  comparison <- match.arg(
    arg = comparison,
    choices = c(
      "difference",
      "levels"
    )
  )
  center <- match.arg(
    arg = center,
    choices = c(
      "mean",
      "median"
    )
  )
  .ValidateMplusDiagThreshold(
    x = rhat_threshold,
    name = "rhat_threshold",
    lower = 1
  )
  .ValidateMplusDiagThreshold(
    x = ess_threshold,
    name = "ess_threshold",
    lower = 0
  )
  .ValidateMplusDiagThreshold(
    x = mcse_threshold,
    name = "mcse_threshold",
    lower = 0
  )
  for (argument in c("relative_mcse", "grey_scale", "values")) {
    value <- get(argument)
    if (
      length(value) != 1L ||
        !is.logical(value) ||
        is.na(value)
    ) {
      stop(
        paste0(
          "`",
          argument,
          "` should be `TRUE` or `FALSE`."
        ),
        call. = FALSE
      )
    }
  }
  metric_data <- .BuildMplusDiagHeatmapData(
    diagnostics = diagnostics,
    metric_name = metric_name,
    comparison = comparison,
    diagnostic = diagnostic,
    taskid = taskid,
    parm = parm,
    center = center,
    rhat_threshold = rhat_threshold,
    ess_threshold = ess_threshold,
    mcse_threshold = mcse_threshold,
    relative_mcse = relative_mcse
  )
  plot_data <- metric_data$data
  legend_spec <- .MplusDiagHeatmapLegendSpec(
    x = plot_data$fill_value,
    metric_name = metric_name,
    comparison = comparison
  )
  legend_guide <- ggplot2::guide_colorbar(
    title.position = "top",
    title.hjust = 0.5,
    label.position = "bottom",
    barwidth = grid::unit(7, "cm"),
    barheight = grid::unit(0.45, "cm")
  )
  if (metric_data$scale_type == "sequential") {
    if (grey_scale) {
      fill_scale <- ggplot2::scale_fill_gradient(
        low = "white",
        high = "grey20",
        limits = legend_spec$limits,
        breaks = legend_spec$breaks,
        labels = legend_spec$labels,
        name = metric_data$legend_title,
        na.value = "grey90",
        guide = legend_guide
      )
    } else {
      fill_scale <- ggplot2::scale_fill_gradient(
        low = "white",
        high = "#B2182B",
        limits = legend_spec$limits,
        breaks = legend_spec$breaks,
        labels = legend_spec$labels,
        name = metric_data$legend_title,
        na.value = "grey90",
        guide = legend_guide
      )
    }
  } else {
    if (grey_scale) {
      fill_scale <- ggplot2::scale_fill_gradient2(
        low = "grey25",
        mid = "white",
        high = "grey70",
        midpoint = 0,
        limits = legend_spec$limits,
        breaks = legend_spec$breaks,
        labels = legend_spec$labels,
        name = metric_data$legend_title,
        na.value = "grey90",
        guide = legend_guide
      )
    } else {
      fill_scale <- ggplot2::scale_fill_gradient2(
        low = metric_data$low_colour,
        mid = "white",
        high = metric_data$high_colour,
        midpoint = 0,
        limits = legend_spec$limits,
        breaks = legend_spec$breaks,
        labels = legend_spec$labels,
        name = metric_data$legend_title,
        na.value = "grey90",
        guide = legend_guide
      )
    }
  }
  heatmap_plot <- ggplot2::ggplot(
    data = plot_data,
    mapping = ggplot2::aes(
      x = condition_label,
      y = parameter_label,
      fill = fill_value
    )
  ) +
    ggplot2::geom_tile(
      color = "white",
      linewidth = 0.25
    )
  if (values) {
    heatmap_plot <- heatmap_plot +
      ggplot2::geom_text(
        mapping = ggplot2::aes(
          label = value_label,
          color = text_colour
        ),
        size = 2,
        show.legend = FALSE,
        na.rm = TRUE
      ) +
      ggplot2::scale_color_identity()
  }
  if (comparison == "levels") {
    heatmap_plot <- heatmap_plot +
      ggplot2::facet_grid(
        rows = ggplot2::vars(
          heterogeneity_label,
          target
        ),
        cols = ggplot2::vars(
          diagnostic_panel,
          method
        ),
        scales = "free_y",
        space = "free_y"
      )
  } else {
    heatmap_plot <- heatmap_plot +
      ggplot2::facet_grid(
        rows = ggplot2::vars(
          heterogeneity_label,
          target
        ),
        cols = ggplot2::vars(diagnostic_panel),
        scales = "free_y",
        space = "free_y"
      )
  }
  heatmap_plot +
    fill_scale +
    ggplot2::labs(
      title = metric_data$title,
      subtitle = metric_data$subtitle,
      caption = metric_data$caption,
      x = NULL,
      y = NULL
    ) +
    .FigTheme(base_size = 10) +
    ggplot2::theme(
      legend.box = "vertical",
      legend.box.just = "center",
      legend.title = ggplot2::element_text(
        face = "bold",
        hjust = 0.5
      ),
      legend.text = ggplot2::element_text(size = 8)
    )
}


.MplusDiagHeatmapLegendSpec <- function(x,
                                        metric_name,
                                        comparison) {
  if (metric_name == "failure_rate") {
    if (comparison == "levels") {
      return(
        list(
          limits = c(0, 1),
          breaks = c(0, 0.5, 1),
          labels = c("0%", "50%", "100%")
        )
      )
    }
    return(
      list(
        limits = c(-1, 1),
        breaks = c(-1, 0, 1),
        labels = c("-100 pp", "0 pp", "+100 pp")
      )
    )
  }

  finite <- x[is.finite(x)]
  maximum <- if (length(finite) == 0L) {
    1
  } else {
    max(abs(finite))
  }
  if (!is.finite(maximum) || maximum <= 0) {
    maximum <- 1
  }

  breaks <- c(-maximum, 0, maximum)
  labels <- if (metric_name == "ess") {
    c(
      sprintf("%+.0f", -maximum),
      "0",
      sprintf("%+.0f", maximum)
    )
  } else {
    decimals <- if (maximum < 0.01) 3L else if (maximum < 0.1) 2L else 1L
    format_signed <- function(value) {
      formatC(
        value,
        format = "f",
        digits = decimals,
        flag = "+"
      )
    }
    c(
      format_signed(-maximum),
      formatC(0, format = "f", digits = decimals),
      format_signed(maximum)
    )
  }

  list(
    limits = c(-maximum, maximum),
    breaks = breaks,
    labels = labels
  )
}

.BuildMplusDiagHeatmapData <- function(diagnostics,
                                       metric_name,
                                       comparison,
                                       diagnostic,
                                       taskid,
                                       parm,
                                       center,
                                       rhat_threshold,
                                       ess_threshold,
                                       mcse_threshold,
                                       relative_mcse) {
  parameter_runs <- .MplusDiagnosticsHeatmapRows(diagnostics)
  parameter_runs <- .FilterMplusDiagHeatmapTask(
    x = parameter_runs,
    taskid = taskid
  )
  dictionary <- .MplusDiagHeatmapParmDict()
  selected_parameters <- .SelectMplusDiagHeatmapParms(
    parameters = data.frame(
      parameter = dictionary$parameter,
      stringsAsFactors = FALSE
    ),
    parm = parm
  )$parameter
  parameter_runs <- parameter_runs[
    parameter_runs$parameter %in% selected_parameters, ,
    drop = FALSE
  ]
  if (nrow(parameter_runs) == 0L) {
    stop(
      "No Mplus parameter diagnostics remained after filtering.",
      call. = FALSE
    )
  }
  long <- .LongMplusDiagnosticsHeatmap(
    x = parameter_runs,
    metric_name = metric_name,
    rhat_threshold = rhat_threshold,
    ess_threshold = ess_threshold,
    mcse_threshold = mcse_threshold,
    relative_mcse = relative_mcse
  )
  available_diagnostics <- unique(long$diagnostic)
  if (!is.null(diagnostic)) {
    if (!is.character(diagnostic) || length(diagnostic) == 0L) {
      stop(
        "`diagnostic` should be `NULL` or contain diagnostic names.",
        call. = FALSE
      )
    }
    missing_diagnostic <- setdiff(
      diagnostic,
      available_diagnostics
    )
    if (length(missing_diagnostic) > 0L) {
      stop(
        paste0(
          "Unknown diagnostic panels were requested: ",
          paste(missing_diagnostic, collapse = ", "),
          ". Available panels are: ",
          paste(available_diagnostics, collapse = ", "),
          "."
        ),
        call. = FALSE
      )
    }
    long <- long[
      long$diagnostic %in% diagnostic, ,
      drop = FALSE
    ]
    diagnostic_levels <- diagnostic
  } else {
    diagnostic_levels <- available_diagnostics
  }
  if (comparison == "difference") {
    long <- .PairMplusDiagnosticsHeatmap(long)
  }
  plot_data <- .SummarizeMplusDiagHeatmap(
    x = long,
    comparison = comparison,
    center = center,
    binary = identical(metric_name, "failure_rate")
  )
  plot_data <- .LabelMplusDiagnosticsHeatmap(
    x = plot_data,
    parameter_dictionary = dictionary,
    selected_parameters = selected_parameters,
    diagnostic_levels = diagnostic_levels,
    comparison = comparison
  )
  plot_data$value_label <- .FormatMplusDiagHeatmapValue(
    value = plot_data$value,
    metric_name = metric_name,
    comparison = comparison
  )
  scale_info <- .MplusDiagnosticsHeatmapScale(
    metric_name = metric_name,
    comparison = comparison,
    threshold = switch(metric_name,
      failure_rate = 0,
      rhat = rhat_threshold,
      ess = ess_threshold,
      mcse = mcse_threshold
    )
  )
  plot_data$fill_value <- if (
    comparison == "levels" &&
      metric_name != "failure_rate"
  ) {
    plot_data$value - scale_info$threshold
  } else {
    plot_data$value
  }
  plot_data$text_colour <- .MplusDiagHeatmapTextColour(
    x = plot_data$fill_value,
    diverging = identical(scale_info$scale_type, "diverging")
  )
  title <- switch(metric_name,
    failure_rate = paste(
      "Bayesian diagnostic failure rates across simulation conditions"
    ),
    rhat = paste(
      "Bayesian R-hat diagnostics across simulation conditions"
    ),
    ess = paste(
      "Bayesian effective sample sizes across simulation conditions"
    ),
    mcse = paste(
      "Bayesian Monte Carlo precision across simulation conditions"
    )
  )
  if (comparison == "difference") {
    title <- paste0(
      title,
      ": prior sensitivity"
    )
    subtitle <- paste0(
      "Cells show paired user-prior minus default-prior summaries across ",
      "replications. Blue indicates improvement with user priors; red ",
      "indicates deterioration."
    )
  } else {
    subtitle <- paste0(
      "Cells show replication ",
      if (metric_name == "failure_rate") "means" else center,
      " within each design cell."
    )
  }
  caption <- switch(metric_name,
    failure_rate = paste0(
      "Failures use R-hat > ",
      format(rhat_threshold, trim = TRUE),
      ", ESS < ",
      format(ess_threshold, trim = TRUE),
      ", and ",
      if (relative_mcse) "relative " else "",
      "MCSE > ",
      format(mcse_threshold, trim = TRUE),
      ". Nonfinite diagnostics count as failures."
    ),
    rhat = paste0(
      "The fill is centered at R-hat = ",
      format(rhat_threshold, trim = TRUE),
      "."
    ),
    ess = paste0(
      "The fill is centered at ESS = ",
      format(ess_threshold, trim = TRUE),
      "."
    ),
    mcse = paste0(
      if (relative_mcse) {
        "MCSE is divided by the posterior SD. "
      } else {
        "MCSE is on the parameter scale. "
      },
      "The fill is centered at ",
      format(mcse_threshold, trim = TRUE),
      "."
    )
  )
  list(
    data = plot_data,
    title = title,
    subtitle = subtitle,
    caption = caption,
    legend_title = scale_info$legend_title,
    scale_type = scale_info$scale_type,
    low_colour = scale_info$low_colour,
    high_colour = scale_info$high_colour
  )
}

.MplusDiagnosticsHeatmapRows <- function(x) {
  if (
    inherits(x, "manmetavar.mplus.diagnostics.all") ||
      (
        is.list(x) &&
          !is.null(x$parameters) &&
          is.data.frame(x$parameters)
      )
  ) {
    x <- x$parameters
  }
  if (!is.data.frame(x)) {
    stop(
      paste0(
        "`diagnostics` should be an all-task diagnostics object or a ",
        "parameter-level data frame."
      ),
      call. = FALSE
    )
  }
  required <- c(
    "taskid",
    "repid",
    "n",
    "time",
    "heterogeneity",
    "default_priors",
    "parameter",
    "sd",
    "rhat",
    "ess_bulk",
    "ess_tail",
    "mcse_mean",
    "mcse_median",
    "mcse_ll",
    "mcse_ul"
  )
  missing <- setdiff(
    required,
    names(x)
  )
  if (length(missing) > 0L) {
    stop(
      paste0(
        "Parameter diagnostics are missing: ",
        paste(missing, collapse = ", "),
        "."
      ),
      call. = FALSE
    )
  }
  if (anyNA(x$default_priors)) {
    stop(
      "`default_priors` should not contain missing values.",
      call. = FALSE
    )
  }
  x$default_priors <- as.logical(x$default_priors)
  x$method <- ifelse(
    x$default_priors,
    "BMLVAR-Default",
    "BMLVAR-Priors"
  )
  key <- x[
    c(
      "taskid",
      "repid",
      "default_priors",
      "parameter"
    )
  ]
  if (anyDuplicated(key)) {
    stop(
      "Parameter diagnostics contain duplicated replication rows.",
      call. = FALSE
    )
  }
  x
}

.LongMplusDiagnosticsHeatmap <- function(x,
                                         metric_name,
                                         rhat_threshold,
                                         ess_threshold,
                                         mcse_threshold,
                                         relative_mcse) {
  metadata <- c(
    "taskid",
    "repid",
    "method",
    "default_priors",
    "n",
    "time",
    "heterogeneity",
    "parameter"
  )
  mcse_names <- c(
    "mcse_mean",
    "mcse_median",
    "mcse_ll",
    "mcse_ul"
  )
  mcse_labels <- c(
    "Posterior mean",
    "Posterior median",
    "Lower interval limit",
    "Upper interval limit"
  )
  mcse_values <- lapply(
    X = mcse_names,
    FUN = function(name) {
      value <- x[[name]]
      if (relative_mcse) {
        value <- ifelse(
          is.finite(x$sd) & x$sd > 0,
          value / x$sd,
          NA_real_
        )
      }
      value
    }
  )
  names(mcse_values) <- mcse_names
  if (metric_name == "rhat") {
    return(
      data.frame(
        x[metadata],
        diagnostic = "R-hat",
        value = x$rhat,
        row.names = NULL,
        check.names = FALSE
      )
    )
  }
  if (metric_name == "ess") {
    return(
      rbind(
        data.frame(
          x[metadata],
          diagnostic = "Bulk ESS",
          value = x$ess_bulk,
          row.names = NULL,
          check.names = FALSE
        ),
        data.frame(
          x[metadata],
          diagnostic = "Tail ESS",
          value = x$ess_tail,
          row.names = NULL,
          check.names = FALSE
        )
      )
    )
  }
  if (metric_name == "mcse") {
    out <- do.call(
      what = "rbind",
      args = lapply(
        X = seq_along(mcse_names),
        FUN = function(i) {
          data.frame(
            x[metadata],
            diagnostic = mcse_labels[i],
            value = mcse_values[[i]],
            row.names = NULL,
            check.names = FALSE
          )
        }
      )
    )
    rownames(out) <- NULL
    return(out)
  }
  rhat_failure <- !is.finite(x$rhat) |
    x$rhat > rhat_threshold
  bulk_failure <- !is.finite(x$ess_bulk) |
    x$ess_bulk < ess_threshold
  tail_failure <- !is.finite(x$ess_tail) |
    x$ess_tail < ess_threshold
  mcse_matrix <- do.call(
    what = "cbind",
    args = mcse_values
  )
  mcse_failure <- apply(
    X = mcse_matrix,
    MARGIN = 1L,
    FUN = function(z) {
      any(!is.finite(z)) || any(z > mcse_threshold)
    }
  )
  any_failure <- rhat_failure |
    bulk_failure |
    tail_failure |
    mcse_failure
  rbind(
    data.frame(
      x[metadata],
      diagnostic = "Any diagnostic",
      value = as.numeric(any_failure),
      row.names = NULL,
      check.names = FALSE
    ),
    data.frame(
      x[metadata],
      diagnostic = "R-hat",
      value = as.numeric(rhat_failure),
      row.names = NULL,
      check.names = FALSE
    ),
    data.frame(
      x[metadata],
      diagnostic = "Bulk ESS",
      value = as.numeric(bulk_failure),
      row.names = NULL,
      check.names = FALSE
    ),
    data.frame(
      x[metadata],
      diagnostic = "Tail ESS",
      value = as.numeric(tail_failure),
      row.names = NULL,
      check.names = FALSE
    ),
    data.frame(
      x[metadata],
      diagnostic = if (relative_mcse) "Relative MCSE" else "MCSE",
      value = as.numeric(mcse_failure),
      row.names = NULL,
      check.names = FALSE
    )
  )
}

.PairMplusDiagnosticsHeatmap <- function(x) {
  keys <- c(
    "taskid",
    "repid",
    "parameter",
    "diagnostic"
  )
  if (anyDuplicated(x[c(keys, "default_priors")])) {
    stop(
      "Diagnostic rows are duplicated within a prior condition.",
      call. = FALSE
    )
  }
  default <- x[x$default_priors, , drop = FALSE]
  priors <- x[!x$default_priors, , drop = FALSE]
  if (nrow(default) == 0L || nrow(priors) == 0L) {
    stop(
      paste0(
        "`comparison = \"difference\"` requires both default- and ",
        "user-prior diagnostics."
      ),
      call. = FALSE
    )
  }
  paired <- merge(
    x = default,
    y = priors,
    by = keys,
    suffixes = c(
      "_default",
      "_priors"
    ),
    all = FALSE,
    sort = FALSE
  )
  if (nrow(paired) == 0L) {
    stop(
      "No matched default- and user-prior diagnostic rows were found.",
      call. = FALSE
    )
  }
  pick <- function(name) {
    default_name <- paste0(name, "_default")
    priors_name <- paste0(name, "_priors")
    default_value <- paired[[default_name]]
    priors_value <- paired[[priors_name]]
    ifelse(
      is.na(default_value),
      priors_value,
      default_value
    )
  }
  data.frame(
    taskid = paired$taskid,
    repid = paired$repid,
    method = "Priors - Default",
    default_priors = NA,
    n = pick("n"),
    time = pick("time"),
    heterogeneity = pick("heterogeneity"),
    parameter = paired$parameter,
    diagnostic = paired$diagnostic,
    value = paired$value_priors - paired$value_default,
    row.names = NULL,
    check.names = FALSE
  )
}

.SummarizeMplusDiagHeatmap <- function(x,
                                       comparison,
                                       center,
                                       binary) {
  group_names <- c(
    "taskid",
    "method",
    "parameter",
    "diagnostic"
  )
  output_names <- c(
    "taskid",
    "method",
    "n",
    "time",
    "heterogeneity",
    "parameter",
    "diagnostic"
  )
  group <- interaction(
    x[group_names],
    drop = TRUE,
    lex.order = TRUE
  )
  split_data <- split(
    x = x,
    f = group,
    drop = TRUE
  )
  out <- lapply(
    X = split_data,
    FUN = function(z) {
      values <- z$value
      if (binary) {
        value <- mean(values)
        n_valid <- length(values)
      } else {
        values <- values[is.finite(values)]
        n_valid <- length(values)
        value <- if (n_valid == 0L) {
          NA_real_
        } else if (center == "median") {
          stats::median(values)
        } else {
          mean(values)
        }
      }
      first <- z[1, output_names, drop = FALSE]
      data.frame(
        first,
        value = value,
        n_valid = n_valid,
        comparison = comparison,
        row.names = NULL,
        check.names = FALSE
      )
    }
  )
  out <- do.call(
    what = "rbind",
    args = out
  )
  rownames(out) <- NULL
  out
}

.LabelMplusDiagnosticsHeatmap <- function(x,
                                          parameter_dictionary,
                                          selected_parameters,
                                          diagnostic_levels,
                                          comparison) {
  parameter_location <- match(
    x$parameter,
    parameter_dictionary$parameter
  )
  if (anyNA(parameter_location)) {
    stop(
      paste0(
        "Unknown Mplus diagnostic parameters were found: ",
        paste(
          unique(x$parameter[is.na(parameter_location)]),
          collapse = ", "
        ),
        "."
      ),
      call. = FALSE
    )
  }
  x$parameter_label <- parameter_dictionary$parameter_label[
    parameter_location
  ]
  x$target <- parameter_dictionary$target[
    parameter_location
  ]
  condition_dictionary <- unique(
    x[
      c(
        "taskid",
        "n",
        "time",
        "heterogeneity"
      )
    ]
  )
  condition_dictionary <- condition_dictionary[
    order(
      condition_dictionary$heterogeneity,
      condition_dictionary$taskid
    ), ,
    drop = FALSE
  ]
  if (anyDuplicated(condition_dictionary$taskid)) {
    stop(
      "Each task ID should identify one simulation design condition.",
      call. = FALSE
    )
  }
  condition_dictionary$condition_label <- ifelse(
    is.na(condition_dictionary$time),
    paste0(
      "N = ",
      condition_dictionary$n,
      ", T = Unbalanced"
    ),
    paste0(
      "N = ",
      condition_dictionary$n,
      ", T = ",
      as.integer(condition_dictionary$time)
    )
  )
  condition_dictionary$heterogeneity_label <- paste0(
    "Het = ",
    format(
      condition_dictionary$heterogeneity,
      trim = TRUE,
      scientific = FALSE
    )
  )
  condition_location <- match(
    x$taskid,
    condition_dictionary$taskid
  )
  x$condition_label <- condition_dictionary$condition_label[
    condition_location
  ]
  x$heterogeneity_label <- condition_dictionary$heterogeneity_label[
    condition_location
  ]
  selected_dictionary <- parameter_dictionary[
    parameter_dictionary$parameter %in% selected_parameters, ,
    drop = FALSE
  ]
  x$parameter_label <- factor(
    x$parameter_label,
    levels = rev(selected_dictionary$parameter_label)
  )
  x$target <- factor(
    x$target,
    levels = c(
      "Innovation",
      "FE",
      "RE"
    )
  )
  x$condition_label <- factor(
    x$condition_label,
    levels = unique(condition_dictionary$condition_label)
  )
  x$heterogeneity_label <- factor(
    x$heterogeneity_label,
    levels = unique(condition_dictionary$heterogeneity_label)
  )
  x$diagnostic_panel <- factor(
    x$diagnostic,
    levels = diagnostic_levels
  )
  x$method <- factor(
    x$method,
    levels = if (comparison == "levels") {
      c(
        "BMLVAR-Default",
        "BMLVAR-Priors"
      )
    } else {
      "Priors - Default"
    }
  )
  x
}

.MplusDiagHeatmapParmDict <- function() {
  data.frame(
    parameter = c(
      "psi[1,1]",
      "psi[2,1]",
      "psi[2,2]",
      "mean(beta[1,1])",
      "mean(beta[2,1])",
      "mean(beta[1,2])",
      "mean(beta[2,2])",
      "mean(mu[1,1])",
      "mean(mu[2,1])",
      "cov(beta[1,1],beta[1,1])",
      "cov(beta[2,1],beta[1,1])",
      "cov(beta[2,1],beta[2,1])",
      "cov(beta[1,2],beta[1,1])",
      "cov(beta[1,2],beta[2,1])",
      "cov(beta[1,2],beta[1,2])",
      "cov(beta[2,2],beta[1,1])",
      "cov(beta[2,2],beta[2,1])",
      "cov(beta[2,2],beta[1,2])",
      "cov(beta[2,2],beta[2,2])",
      "cov(mu[1,1],mu[1,1])",
      "cov(mu[2,1],mu[1,1])",
      "cov(mu[2,1],mu[2,1])"
    ),
    parameter_label = c(
      "Var(Innovation 1)",
      "Cov(Innovation 1, Innovation 2)",
      "Var(Innovation 2)",
      "AR 1->1",
      "CL 1->2",
      "CL 2->1",
      "AR 2->2",
      "SP 1",
      "SP 2",
      "Var(AR 1->1)",
      "Cov(AR 1->1, CL 1->2)",
      "Var(CL 1->2)",
      "Cov(AR 1->1, CL 2->1)",
      "Cov(CL 1->2, CL 2->1)",
      "Var(CL 2->1)",
      "Cov(AR 1->1, AR 2->2)",
      "Cov(CL 1->2, AR 2->2)",
      "Cov(CL 2->1, AR 2->2)",
      "Var(AR 2->2)",
      "Var(SP 1)",
      "Cov(SP 1, SP 2)",
      "Var(SP 2)"
    ),
    target = c(
      rep("Innovation", 3L),
      rep("FE", 6L),
      rep("RE", 13L)
    ),
    stringsAsFactors = FALSE
  )
}

.MplusDiagnosticsHeatmapScale <- function(metric_name,
                                          comparison,
                                          threshold) {
  if (comparison == "difference") {
    if (metric_name == "ess") {
      low_colour <- "#B2182B"
      high_colour <- "#2166AC"
    } else {
      low_colour <- "#2166AC"
      high_colour <- "#B2182B"
    }
    return(
      list(
        scale_type = "diverging",
        threshold = 0,
        legend_title = "User - default",
        low_colour = low_colour,
        high_colour = high_colour
      )
    )
  }
  if (metric_name == "failure_rate") {
    return(
      list(
        scale_type = "sequential",
        threshold = 0,
        legend_title = "Failure rate",
        low_colour = "white",
        high_colour = "#B2182B"
      )
    )
  }
  if (metric_name == "ess") {
    low_colour <- "#B2182B"
    high_colour <- "#2166AC"
  } else {
    low_colour <- "#2166AC"
    high_colour <- "#B2182B"
  }
  list(
    scale_type = "diverging",
    threshold = threshold,
    legend_title = paste0(
      switch(metric_name,
        rhat = "R-hat",
        ess = "ESS",
        mcse = "MCSE"
      ),
      " - ",
      format(threshold, trim = TRUE)
    ),
    low_colour = low_colour,
    high_colour = high_colour
  )
}

.FormatMplusDiagHeatmapValue <- function(value,
                                         metric_name,
                                         comparison) {
  if (metric_name == "failure_rate") {
    if (comparison == "difference") {
      return(
        ifelse(
          is.finite(value),
          sprintf("%+.0f pp", 100 * value),
          NA_character_
        )
      )
    }
    return(
      ifelse(
        is.finite(value),
        sprintf("%.0f%%", 100 * value),
        NA_character_
      )
    )
  }
  if (metric_name == "ess") {
    return(
      ifelse(
        is.finite(value),
        if (comparison == "difference") {
          sprintf("%+.0f", value)
        } else {
          sprintf("%.0f", value)
        },
        NA_character_
      )
    )
  }
  ifelse(
    is.finite(value),
    if (comparison == "difference") {
      sprintf("%+.3f", value)
    } else {
      sprintf("%.3f", value)
    },
    NA_character_
  )
}

.MplusDiagHeatmapTextColour <- function(x,
                                        diverging) {
  finite <- x[is.finite(x)]
  if (length(finite) == 0L) {
    return(rep("black", length(x)))
  }
  if (diverging) {
    boundary <- 0.65 * max(abs(finite))
    if (!is.finite(boundary) || boundary == 0) {
      return(rep("black", length(x)))
    }
    ifelse(
      is.finite(x) & abs(x) >= boundary,
      "white",
      "black"
    )
  } else {
    boundary <- unname(
      stats::quantile(
        finite,
        probs = 0.75,
        names = FALSE,
        type = 8
      )
    )
    ifelse(
      is.finite(x) & x >= boundary,
      "white",
      "black"
    )
  }
}

.ValidateMplusDiagThreshold <- function(x,
                                        name,
                                        lower) {
  if (
    length(x) != 1L ||
      !is.numeric(x) ||
      !is.finite(x) ||
      x <= lower
  ) {
    stop(
      paste0(
        "`",
        name,
        "` should be a finite numeric value greater than ",
        lower,
        "."
      ),
      call. = FALSE
    )
  }
  invisible(x)
}

.FilterMplusDiagHeatmapTask <- function(x,
                                        taskid = NULL) {
  if (is.null(taskid)) {
    return(x)
  }
  if (
    !is.numeric(taskid) ||
      length(taskid) == 0L ||
      any(!is.finite(taskid)) ||
      any(taskid != floor(taskid)) ||
      any(taskid < 1L)
  ) {
    stop(
      "`taskid` should contain positive integers.",
      call. = FALSE
    )
  }
  out <- x[x$taskid %in% as.integer(taskid), , drop = FALSE]
  if (nrow(out) == 0L) {
    stop(
      "No parameter diagnostics matched the requested `taskid` values.",
      call. = FALSE
    )
  }
  out
}

.SelectMplusDiagHeatmapParms <- function(parameters,
                                         parm = NULL) {
  if (!is.data.frame(parameters) || !"parameter" %in% names(parameters)) {
    stop(
      "`parameters` should be a data frame containing `parameter`.",
      call. = FALSE
    )
  }
  if (anyDuplicated(parameters$parameter)) {
    stop(
      "Parameter names in `parameters` should be unique.",
      call. = FALSE
    )
  }
  if (is.null(parm)) {
    return(parameters)
  }
  if (length(parm) == 0L) {
    stop(
      "`parm` should select at least one parameter.",
      call. = FALSE
    )
  }
  if (is.numeric(parm)) {
    if (
      any(!is.finite(parm)) ||
        any(parm != floor(parm)) ||
        any(parm < 1L) ||
        any(parm > nrow(parameters))
    ) {
      stop(
        "Numeric `parm` values should be valid positive integer positions.",
        call. = FALSE
      )
    }
    location <- as.integer(parm)
  } else if (is.character(parm)) {
    location <- match(parm, parameters$parameter)
    if (anyNA(location)) {
      stop(
        paste0(
          "Unknown parameters were requested: ",
          paste(unique(parm[is.na(location)]), collapse = ", "),
          "."
        ),
        call. = FALSE
      )
    }
  } else {
    stop(
      "`parm` should be `NULL`, numeric positions, or parameter names.",
      call. = FALSE
    )
  }
  parameters[unique(location), , drop = FALSE]
}
